# Formas open access  

> Retirar las barreras de acceso a esta literatura acelerará la investigación, enriquecerá la educación, compartirá el aprendizaje de los ricos con los pobres y el de los pobres con el de los ricos, hará esta literatura tan útil como sea posible y sentará los cimientos para unir a la humanidad en una conversación intelectual común y búsqueda del conocimiento. (Budapest Open Access Initiative, 2012)

## ¿Qué es open access?  

**_Open Acces (OA)_** es un movimiento científico cuyo objetivo es promover el libre acceso a la producción científica digital y hacer uso de ella sin restricciones de *copyright.* Los primeros vestigios del **OA** aparecieron a la par con la creación del internet, pero no fue hasta el 2002 con la declaración de Budapest que se definió el concepto de **OA**. Posteriormente en 2003 las declaraciones de Bethesda y Berlín sumaron argumentos para el marco de referencia del *OA*. Las causas que gatillan el desarrollo de *OA* son principalmente dos: [(Melero, R. y Abad, M. 2008)](https://bid.ub.edu/20meler2.htm)  

1. La constitución del internet y las nuevas tecnologías como el medeio para la divulgación cinetífica.  

2. Los elevados precios de suscripción a revistas cinetíficas digitales se presentaron como barreras económicas y de copyright al acceso de publicaciones cinetíficas.  

## ¿Qué y cómo se publica en open access?   

Cualquier contenido digital puede ser publicado con **Aceso Abierto (OA)**, ya sea académico (pre-print, publicaciones finales, libros, capítulos de libros, bases de datos, softwares, etc.) como artístico-cultural (películas, música, literatura, etc.), sin embargo, esto no se encuentra excento de licencias y se recomienda el uso de CC-By. 

> Esta licencia (CC-BY) permite que otros distribuyan, mezclen, adapten y construyan sobre su trabajo, incluso comercialmente, siempre que le reconozcan la creación original. Esta es la licencia más complaciente que se ofrece. Recomendado para la máxima difusión y uso de materiales con licencia. (Creative Commons, 2017)

Cualquier tipo de producción cinetífica puede ser compartida libremente en plataformas digitales, pero a ello no se le atribuye como una práctica de **Aceso Abierto**. En 2013, UNESCO estableció dos tipos de repositorios, las cuales sirven como rutas formalmente aceptables para compartir publicaciones científicas con el rotulo de **OA** [(Swan, A. 2013)](https://unesdoc.unesco.org/ark:/48223/pf0000222536).  

1. **Repositorios de Vía Verde**: Consiste en un proceso de "auto-archivo o auto-depósito" donde los/as autores/as comparten sus post-print (Artículo final) en sus páginas personales o en revistas que no son gratuitas pero que poseen repositorios de acceso libre. Estos repositorios antes mencionados se adhieren a un conjunto de reglas técnicas de interoperación, por ello forman una red interconectada de bases de datos que pueden ser de tres tipos distintos:  

    + *Conocimientos destallados (específicos):*  Los repositorios de temas específicos se consolidan por medio de dos formas, cuando los/as autores/as transfieren directamente sus trabajos en el repositorio o estos recolectan publicaciones de otras colecciones para centralizarlos.  
  
    + *Institucionales:* Corresponde a un repositorio particular de cada universidad o instituto de investigación.  
  
    + *De datos:* Son plataformas que se dedican principalmente a la centralización de datos de investigación.

2. **Repositorios de vía Dorada**: corresponden a repositorios que publican trabajos de investigación en forma gratuita para el/la Lector/a. En este sentido, el cobro asociado a la publicación lo costean los/as autores/as o las instituciones a las que se asocian. Por lo general, se especializan mayormente en la publicación sobre temas de salud y georgrafía, siendo de tres tipos:  

    + *Revistas Pagadas:* liberan el acceso de las publicaciones con previo pago del/la autor/a o de la institución que le respalde.
    
    + *Revistas Libres:* Refiere a cuando los productos científicos son compartidos en sitios públicos como páginas personales, sitios universitarios u otros. Sin embargo, estos sitios -en su mayoría- carecen de sistemas de etiquetado o bien, no cumplen con los estandares del protocolo OAI-PMH.
    
    + *Revistas Híbridas:* Gran parte de las editoriales académicas utilizan este modelo con el objetivo de ofrecer Acceso Abierto al mismo tiempo en el que mantienen su modelo de negocio habitual basado en suscripciones. Esto permite a los autores optar por pagar una cuota de publicación y  tener sus artículos creados con Acceso Abierto en revistas por suscripción.
    
## Revistas de acceso abierto:

### ResearchGate y Academia.edu: ¿Plataformas de aceso abierto?

Las plataformas de _ResearchGate y Academia.edu_ son parte del conocimiento común de todo/a investigador/a y quizás en más de alguna ocasión hemos recurrido a estas páginas para recuperar archivos científicos para nuestro uso personal. Sin embargo, hay que mencionar que estas plataformas no son un ejemplo de *Open Acess* debido a dos principales características descritas por [Fortney, K. y Gonder, J. (2015)](https://osc.universityofcalifornia.edu/2015/12/a-social-networking-site-is-not-an-open-access-repository/):  

1. _ResearchGate y Academia.edu_ funcionan de forma similar a _Facebook o LinkedIn_, o sea como _redes sociales académicas_ cuyo objetivo es conectar a investigadores/as con interes comunes y compartir copias de sus productos elaborados.  

2. _ResearchGate y Academia.edu_ son empresas con fines de lucro y por lo tanto, existe la posibilidad de que cierren en algún momento. Mientras que los repositorios de *Aceso Abierto* por lo general son administrados por universidades, agencias gubernamentales, asociaciones internacionales u cualquier otro organismo sin fines de lucro, cuyo objetivo se centra el poner los conocimietos al servicio público.  

### Repositorios de Revistas OA:

Con la invención del internet también aumentaron las oportunidades de divulgación científica, y si bien el concepto de **OA** no fue precisado hasta los 2000, en la década anterior ya venían gestandose proyectos como _The public-access computer systems review (1990)_, una revista electrónica tipo boletín que era distribuída por correo electrónico. Posteriormente, en 1991 revistas como _Surfaces y Psycoloquy_ fueron pioneras en instalar la metodología de acceso gratuito a sus publicaciones. Hoy en día son muchos los sitios de repositorios que cumplen con políticas de *Aceso Abierto*, pero con licencias particulares que es necesario conocer para adentrarnos en su uso.

revistas y politicas: (MDA de Gesis, etc). Sería bueno tener algún listado acotado de SOCArvix (buscador Sherpa) (!!!)


## ¿Qué pasa si no es de acceso  abierto y quiero abrir igual?  

En el capítulo 1 abordamos el rol de la propiedad intelectual en materias de investigación científica puesto a que, es la piedra angular para adentrarse en el _Aceso Abierto_ y para negociar con las revistas los límites de acción de cada contraparte. Por lo general, al realizar el envío de un artículo a una revista, el/la autor/a firma un _Acuerdo de Transferencia de Derechos (CTA)_, transfiriendole al editor/a los derechos de autor sobre la obra y por lo tanto, imposibilitando toda acción del propio/a creador/a sobre la investigación. Para que la decisión de publicar dentro de una revista no afecte a la posterior decisión de abrir la publicación, por una parte los editores deben tener una licencia que sirve únicamente para publicar (LTP) y, por otra parte, los/as autores/as deben retener para si los derechos sobre la obra.

En síntesis, para que cualquier recurso científico sea abierto, este debe contener una licencia que explicite a los/as usuarios/as las acciones que pueden realizar sobre la obra e indicar la correcta acreditación de la fuente [(Swan, A. 2013)](https://unesdoc.unesco.org/ark:/48223/pf0000222536).


### Razones para utilizar open-access ("el cierre de la triada") (!!!)

El uso amplio de la ciencia abierta depende mucho de la disciplina, en el sentido de que las ciencias exactas ligadas al estudio de la tierra, la física y la salud lideran el ranking de publicaciones abiertas, siguiendole el paso las ciencias sociales [(Swan, A. 2013)](https://unesdoc.unesco.org/ark:/48223/pf0000222536). Sin embargo, los beneficios atribuídos a las practicas cientificas de caracter abierto no difieren sobre la disciplina. Según [Hernández, E. (2016)](http://www.scielo.org.mx/scielo.php?script=sci_arttext&pid=S2448-87712016000100002), el desarrollo del conocimiento científico dentro del marco del Acceso Abierto trae consigo múltiples beneficios que se asocian a:

  + Costos más bajos en relación a la impresión del documento y su envío.
  + Mayor accesibilidad y conservación de los productos científicos.
  + Difusión rápida e inmediata de la publicaciones.
  + Facilita la comunicación directa de los conocimientos científicos ayudando a avanzar un mejoramiento de la calidad en la investigación.
  + Posibilita reutilizar información, datos y procesos.


 Discusión sobre los  conocimientos comunes(!!!)

## Referencias  

[Budapest Open Access Initiative (14 de Febrero 2002). Iniciativa de Budapest para el Acceso Abierto. (Trad.) En Budapest, HUngría.](hhttps://www.budapestopenaccessinitiative.org/translations/spanish-translation)

[Creative Commons (7 de Noviembre 2017). Sobre las licencias: Lo que nuestras licencias hacen.](https://creativecommons.org/licenses/?lang=es)

[Fortney, K. y Gonder, J. (1 de Diciembre 2015). A social networking site is not an open access repository. En Office of Scholarly Communication (web) - University of California](https://osc.universityofcalifornia.edu/2015/12/a-social-networking-site-is-not-an-open-access-repository/)

[Hernández, E. (2016). ¿Por qué Open Acess?. Anestesia en México, 28(1), 2-3. ISSN 2448-8771](http://www.scielo.org.mx/scielo.php?script=sci_arttext&pid=S2448-87712016000100002)

[Melero, R. y Abad, M. (2008). Revistas open access : características, modelos económicos y tendencias. BiD: textos universitaris de biblioteconomia i documentació, núm. 20 (juny)](https://bid.ub.edu/20meler2.htm)  

[Swan, A. (2013). Directrices para Políticas de desarrollo y promoción del Aceso Abierto. UNESCO - ISBN 978-959-18-0928- 5](https://unesdoc.unesco.org/ark:/48223/pf0000222536)

## Otros link de interés

[Peña-López, I. (20 de Junio 2003). Declaración de Bethesda sobre Publicación de Acceso Abierto (Trad.). En Howard Hughes Medical Institute, en Maryland.](https://ictlogy.net/articles/bethesda_es.html)

[Budapest Open Access Initiative (12 de Septiembre 2012). Diez años desde la Budapest Open Access Initiative: hacia lo abierto por defecto (Melero, R. y Babini, D. Trad.).](https://www.budapestopenaccessinitiative.org/boai-10-translations/spanish)  

[Sociedad Max Planck, ed. (2003). La Declaración de Berlín sobre acceso abierto. GeoTrópico, 1 (2), 152-154, versión PDF.](http://www.geotropico.org/1_2_Documentos_Berlin.htm)

[UNESCO (1999). Declaración sobre la ciencia y el uso del saber cinetífico. En Conferencia mundial sobre la ciencia.](http://www.unesco.org/science/wcs/esp/declaracion_s.htm)
